### ISSUE TITLE
有2个输入框         focusLooper: true,         focusLooperDuration: const Duration(seconds: 2) 开起来 会有冲突啊

### ISSUE THREAD

**Issue by WyntersN** [liyufengrex/flutter_scan_gun#11]
body: ScanMonitorWidget(
        focusLooper: true,
        focusLooperDuration: const Duration(seconds: 2),
        textFiledNode: textFiledNode,
        onSubmit: (String value) {
          _controller.search(_refreshController, value);
        },
        childBuilder: (context) {
          return body(context);
        },
      ),
      
      第二个输入框有冲突，第二个输入框输入的内容全部跑到第一个输入框了

**Comment by liyufengrex** [comment]
这个方案不支持这种有多输入框的场景，ScanMonitorWidget 主要是处理无输入框无焦点的场景。如果要在多输入框页面使用 ScanMonitorWidget ， 建议把 ScanMonitorWidget 放在父节点，且 focusLooper 设置为 false， 然后在自己页面监听那两个输入框焦点，如果两个输入框都没有获取焦点，通过 `scanKey.currentState?.requestKeyboard()`，把监听扫码枪的责任还给 ScanMonitorWidget。

**Comment by WyntersN** [comment]
最后 我自己 自定义了 一个键盘才解决问题

**Comment by WyntersN** [comment]
那如果我要手动输入咋办，键盘弹出0.5秒就会自动关闭

**Comment by liyufengrex** [comment]
> 那如果我要手动输入咋办，键盘弹出0.5秒就会自动关闭。

根据你的自定义场景，focusLooper 设置为 false， 结合你自己的焦点，写个逻辑，统一管理扫码焦点，例如将焦点还给扫码焦点：scanKey.currentState?.requestKeyboard()
